version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 25
  reviewers:
  - mprins
  assignees:
  - mprins
  labels:
  - build infrastructure
  - dependencies
  ignore:
  - dependency-name: javax.servlet:javax.servlet-api
    versions:
    - ">= 3.1.a, < 3.2"
  - dependency-name: javax.servlet:javax.servlet-api
    versions:
    - ">= 4.a, < 5"
  - dependency-name: javax.servlet.jsp:javax.servlet.jsp-api
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.apache.lucene:lucene-core
    versions:
    - "> 4.6.0"
  - dependency-name: org.apache.solr:solr-core
    versions:
    - "> 4.6.0"
  - dependency-name: org.apache.solr:solr-core
    versions:
    - ">= 7.a, < 8"
  - dependency-name: org.apache.solr:solr-solrj
    versions:
    - "> 4.6.0"
  - dependency-name: org.apache.solr:solr-solrj
    versions:
    - ">= 7.a, < 8"
  - dependency-name: org.stripesstuff:stripesstuff
    versions:
    - ">= 1.a, < 2"
  - dependency-name: org.apache.tomcat:*
    versions:
    - ">= 10"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: saturday
    timezone: Europe/Amsterdam
  labels:
  - build infrastructure
  - backport v5.8.x

- package-ecosystem: "docker"
  directory: "/src/main/docker/"
  schedule:
    interval: weekly
    timezone: Europe/Amsterdam
    day: "saturday"
  open-pull-requests-limit: 25
  reviewers:
  - mprins
  assignees:
  - mprins
  labels:
  - build infrastructure
