version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 25
    reviewers:
      - mprins
    assignees:
      - mprins
    labels:
      - build infrastructure
      - dependencies
    ignore:
      - dependency-name: org.apache.tomcat:*
        versions:
          - '>= 10'
      - dependency-name: org.apache.tomcat.embed:*
        versions:
          - '>= 10'
      - dependency-name: org.springframework.security:spring-security-crypto
        versions:
          - '>= 6'


  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      timezone: 'Europe/Amsterdam'
    labels:
      - build infrastructure
    assignees:
      - mprins


  - package-ecosystem: docker
    directory: '/src/main/docker/'
    schedule:
      interval: weekly
      timezone: Europe/Amsterdam
      day: monday
    open-pull-requests-limit: 25
    reviewers:
      - mprins
    assignees:
      - mprins
    labels:
      - build infrastructure
    ignore:
      # stay on Tomcat 9 for now
      - dependency-name: 'tomcat'
        versions:
          - '>= 10'
