name: MacOS Maven build

on:
  pull_request:

concurrency:
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS Java 11
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn -B test -fae
        mvn -B verify -fae -e

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Cleanup snapshots
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
