name: Ubuntu Maven build

env:
  PG_PORT: 5432
  PG_HOST: 127.0.0.1
  DB_NAME: tailormap
  DB_USER: tailormap
  DB_PASS: tailormap
  MAIL_FROM: noreply@b3partners.nl
  MAIL_HOST: mail.b3partners.nl
  TM_DATA_DIR: /opt/tailormap_data
  #CATALINA_OPTS:

concurrency:
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ github.workflow }}-${{ ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-master-{0}', github.sha) || format('ci-master-{0}', github.ref) }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "16 23 * * 0"

jobs:
  build:
    name: Ubuntu Java 11 Build
    runs-on: ubuntu-22.04

    services:
      postgres:
        # docker run -h tailormap-db --name tailormap-db -it --rm -d \
        #  -e POSTGRES_USER=${DB_USER} -e POSTGRES_DB=${DB_NAME} -e POSTGRES_PASSWORD=${DB_PASS} -p 5432:5432 postgres:14-alpine
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASS }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 15s --health-timeout 5s --health-retries 5

    steps:
      - name: Check database
        run: |
          psql --version
          echo ${{ env.CATALINA_OPTS }}
          PGPASSWORD=${{ env.DB_PASS }} psql -d ${{ env.DB_NAME }} -h localhost -U ${{ env.DB_USER }} -c 'SELECT Version();' || true

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Priming build with Maven
        run: mvn install -DskipTests -DskipITs -B -V -fae

      - name: Test with Maven
        run: |
          mvn -e clean test -B
          mvn -e verify -B -Pintegration-testing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build javadoc
        run: mvn javadoc:javadoc

      - name: Build test javadoc
        run: mvn javadoc:test-javadoc

      - name: Try running the created Docker image
        #        PG_PORT=5432
        #        PG_HOST=127.0.0.1
        #        DB_NAME=tailormap
        #        DB_USER=tailormap
        #        DB_PASS=tailormap
        #        MAIL_FROM=noreply@b3partners.nl
        #        MAIL_HOST=mail.b3partners.nl
        #        TM_DATA_DIR=/opt/tailormap_data
        #        CATALINA_OPTS="-DPG_PORT=$PG_PORT -DPG_HOST=$PG_HOST -DDB_NAME=$DB_NAME -DDB_USER=$DB_USER -DDB_PASS=$DB_PASS -DMAIL_FROM=$MAIL_FROM -DMAIL_HOST=$MAIL_HOST -DTM_DATA_DIR=$TM_DATA_DIR"
        # note that the docker repo is also defined in the pom file properties as "docker.deploy.repo"
        # echo ${{ env.CATALINA_OPTS }}
        run: |
          docker run --rm -d -e CATALINA_OPTS="-DPG_PORT=${{ env.PG_PORT }} -DPG_HOST=${{ env.PG_HOST }} -DDB_NAME=${{ env.DB_NAME }} -DDB_USER=${{ env.DB_USER }} -DDB_PASS=${{ env.DB_PASS }} -DMAIL_FROM=${{ env.MAIL_FROM }} -DMAIL_HOST=${{ env.MAIL_HOST }} -DTM_DATA_DIR=${{ env.TM_DATA_DIR }}" --network host ghcr.io/b3partners/tailormap-admin:snapshot
          sleep 10
          curl http://localhost:8080/admin/action/admin/upgradecheck/ping

      - name: Deploy artifacts
        if: ${{ github.ref == 'refs/heads/main' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' ) }}
        env:
          REPO_B3P_ACTOR: ${{ secrets.REPO_B3P_ACTOR }}
          REPO_B3P_TOKEN: ${{ secrets.REPO_B3P_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -Pqa-skip --settings .github/maven-settings.xml deploy

      - name: Cleanup Maven cache
        if: ${{ always() }}
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}

