name: Ubuntu Maven build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Ubuntu Java 11 Build
    runs-on: ubuntu-20.04

    services:
      postgres:
        # docker run -h tailormap --name tailormap -it --rm -d -e POSTGRES_USER=tailormap -e POSTGRES_DB=tailormap -e POSTGRES_PASSWORD=tailormap -p 5432:5432 postgres:14.1-alpine
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: tailormap
          POSTGRES_PASSWORD: tailormap
          POSTGRES_DB: tailormap
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 15s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Priming build with Maven
        run: mvn install -DskipTests -DskipITs -B -V -fae

      - name: Test with Maven
        run: |
          mvn -e clean test -B
          mvn -e verify -B -Pgh-action

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Build javadoc
        run: mvn javadoc:javadoc

      - name: Build test javadoc
        run: mvn javadoc:test-javadoc

      - name: Cleanup snapshots
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
